id: rtsp
name: 推流
version: 1.0.0
author: LDD_ROG
icon: app.png
desc: 320*480,30FPS
files:
  - assets\exit_touch.jpg
  - assets\exit.jpg
  - assets\img_eye_close.png
  - assets\img_eye_open.png
  - main.py
